version: "3"

services:
  api:
    build: ./
    image: planning_poker_api
    container_name: planning_poker_api
    env_file:
      - ./.envs/.local/.api
    volumes:
      - .:/code
    ports:
      - 8000:80
    command:  uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 80
    depends_on:
      - postgres

  postgres:
    image: postgres:14.5-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.envs/.local/.postgres

volumes:
  postgres_data: